apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: httpd
spec:
  template:
    metadata:
      name: httpd-frontend
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: http:2.4-alpine
  replicas: 3
  selector:
    matchLabels:
        app: httpd