apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  storageClassName: manual
  accessModes: 
    - 'ReadWriteOnce'
  capacity:
     storage: 1Gi
  hostPath:
     path: '/opt/volume/nginx'
  claimRef:
    name: foo-pvc