apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logger
  name: logger
spec:
  containers:
  - image: nginx:alpine
    name: logger
    resources: {}
    volumeMounts:
      - mountPath: "/var/www/nginx"
        name: log-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
     - name: log-volume
       persistentVolumeClaim:
         claimName: log-claim
status: {}