apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    name: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: nginx
          image: nginx:latest
  replicas: 2